spring.application.name=backend
jwt.secret=mismascotas-super-secret-key-2026

spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.bizlerrpmxojbssgmbma
spring.datasource.password=YRSiAU7HzF8mICmd
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.pre-auth-expiration-minutes=10
auth.codigo-verificacion.expiracion-minutos=10


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=Estebancandio@gmail.com
spring.mail.password=cvnp snys fybo rmec
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000