spring.application.name=backend
jwt.secret=mismascotas-super-secret-key-2026

spring.datasource.url=jdbc:postgresql://db.bizlerrpmxojbssgmbma.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=YRSiAU7HzF8mICmd
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true