import { Alert, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useAppData } from "../context/app-data-context";

const benefits = ["Mascotas ilimitadas", "Historial clínico completo", "Exportar historial en PDF", "Álbumes sin límite", "Recordatorios avanzados"];

export default function PlanPremiumScreen() {
  const router = useRouter();
  const { premium, setPremium } = useAppData();
  const activate = () => { setPremium(true); Alert.alert("Plan Premium activado", "Activación simulada. Más adelante se integrará Mercado Pago."); };
  return <SafeAreaView style={styles.container}><View style={styles.topBar}><TouchableOpacity style={styles.back} onPress={() => router.back()}><Ionicons name="chevron-back" size={24} color="#30293A" /></TouchableOpacity><Text style={styles.topTitle}>Plan Premium</Text><View style={styles.placeholder} /></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.hero}><View style={styles.crown}><Ionicons name="diamond-outline" size={37} color="#FFFFFF" /></View><Text style={styles.heroTitle}>Cuidá sin límites</Text><Text style={styles.heroText}>Más herramientas para acompañar cada momento de tus mascotas.</Text></View><View style={styles.planCard}><View style={styles.planHeader}><View><Text style={styles.planName}>Premium</Text><Text style={styles.planDescription}>Todo lo que necesitás para cuidar mejor.</Text></View><Text style={styles.price}>$ 4.999<Text style={styles.month}> / mes</Text></Text></View>{benefits.map((benefit) => <View key={benefit} style={styles.benefit}><Ionicons name="checkmark-circle" size={20} color="#7C4DFF" /><Text style={styles.benefitText}>{benefit}</Text></View>)}</View><TouchableOpacity style={[styles.button, premium && styles.buttonActive]} onPress={activate}><Text style={styles.buttonText}>{premium ? "Plan Premium activo" : "Activar Premium"}</Text></TouchableOpacity><Text style={styles.note}>Pago simulado. Podés cancelar cuando quieras.</Text></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: "#FAF9FC" }, topBar: { height: 72, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 20 }, back: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF" }, topTitle: { color: "#201B29", fontSize: 17, fontWeight: "800" }, placeholder: { width: 42 }, content: { padding: 20, paddingTop: 8, paddingBottom: 36 }, hero: { alignItems: "center", paddingVertical: 24, backgroundColor: "#7C4DFF", borderRadius: 22, marginBottom: 22 }, crown: { width: 66, height: 66, borderRadius: 33, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,255,255,0.18)" }, heroTitle: { color: "#FFFFFF", fontSize: 24, fontWeight: "800", marginTop: 13 }, heroText: { color: "#E9DFFF", fontSize: 13, textAlign: "center", lineHeight: 19, paddingHorizontal: 30, marginTop: 6 }, planCard: { backgroundColor: "#FFFFFF", borderRadius: 18, padding: 17 }, planHeader: { flexDirection: "row", justifyContent: "space-between", paddingBottom: 16, marginBottom: 9, borderBottomWidth: 1, borderBottomColor: "#F0EDF3" }, planName: { color: "#201B29", fontSize: 20, fontWeight: "800" }, planDescription: { color: "#7E7787", fontSize: 11, marginTop: 3 }, price: { color: "#7C4DFF", fontSize: 18, fontWeight: "800" }, month: { color: "#8D8695", fontSize: 10, fontWeight: "600" }, benefit: { flexDirection: "row", alignItems: "center", gap: 9, paddingVertical: 8 }, benefitText: { color: "#48414F", fontSize: 13 }, button: { height: 53, alignItems: "center", justifyContent: "center", backgroundColor: "#7C4DFF", borderRadius: 14, marginTop: 19 }, buttonActive: { backgroundColor: "#509C75" }, buttonText: { color: "#FFFFFF", fontSize: 15, fontWeight: "800" }, note: { color: "#938C99", fontSize: 11, textAlign: "center", marginTop: 12 } });
